# Generated by Django 2.2.3 on 2019-11-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchedland',
            name='facility',
            field=models.ManyToManyField(to='land.Facility'),
        ),
    ]
