# Generated by Django 2.2.3 on 2019-11-05 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together={('kitchen', 'bedroom', 'hall')},
        ),
    ]
