# Generated by Django 2.2.3 on 2019-11-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20191105_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='bedroom',
            field=models.IntegerField(unique=True),
        ),
    ]
