# Generated by Django 2.2.3 on 2019-11-08 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0004_auto_20191105_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.RoomType')),
            ],
            options={
                'unique_together': {('room_type', 'title')},
            },
        ),
        migrations.CreateModel(
            name='PostedRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('conditon', models.TextField()),
                ('price', models.IntegerField()),
                ('facility', models.ManyToManyField(blank=True, to='room.Facility')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.RoomType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
