# Generated by Django 2.2.3 on 2019-11-08 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_facility_postedroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.PostedRoom'), verbose_name='Image')),
                ('posted_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.PostedRoom')),
            ],
        ),
    ]
