# Generated by Django 2.2.3 on 2019-11-08 05:12

from django.db import migrations, models
import room.models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=room.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='postedroom',
            name='facility',
            field=models.ManyToManyField(blank=True, null=True, to='room.Facility'),
        ),
    ]
