# Generated by Django 2.2.3 on 2019-11-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20191108_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedroom',
            name='contact',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
