# Generated by Django 2.2.3 on 2019-11-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_auto_20191110_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedroom',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
