# Generated by Django 2.2.3 on 2019-11-11 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import room.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0010_auto_20191110_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=room.models.get_image_filename),
        ),
        migrations.CreateModel(
            name='SearchedRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('room_number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
