# Generated by Django 2.2.3 on 2019-11-11 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_auto_20191111_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchedroom',
            name='room_type',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='room.RoomType'),
            preserve_default=False,
        ),
    ]
