# Generated by Django 2.2.3 on 2019-11-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_searchedroom_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchedroom',
            name='room_number',
        ),
    ]
