# Generated by Django 2.2.3 on 2019-11-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_remove_searchedroom_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchedroom',
            name='facility',
            field=models.ManyToManyField(to='room.Facility'),
        ),
    ]
