# Generated by Django 2.2.3 on 2019-11-04 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='applied_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_aplied_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='posted_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_posted_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
