# Generated by Django 2.2.3 on 2019-08-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
