# Generated by Django 2.2.3 on 2019-08-01 05:18

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190730_0959'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='years', unique_with=('id',)),
        ),
        migrations.CreateModel(
            name='PostedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.Experience')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.Facility')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.JobType')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.Skills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
