# Generated by Django 2.2.3 on 2019-08-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobamount',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='jobamount',
            name='jobtype',
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.DeleteModel(
            name='JobAmount',
        ),
    ]
