# Generated by Django 2.2.3 on 2019-09-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtype',
            name='icon',
        ),
        migrations.AddField(
            model_name='jobtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobtypes'),
        ),
    ]
