# Generated by Django 2.2.3 on 2019-08-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='setting')),
                ('about_text', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('website', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='skills',
            field=models.ManyToManyField(blank=True, to='jobs.Skills'),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='facility',
            field=models.ManyToManyField(blank=True, to='jobs.Facility'),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='skills',
            field=models.ManyToManyField(blank=True, to='jobs.Skills'),
        ),
    ]
