# Generated by Django 2.2.3 on 2019-08-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='commission',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
