# Generated by Django 2.2.3 on 2019-11-04 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191104_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobType'),
        ),
    ]
