# Generated by Django 2.2.3 on 2019-08-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190807_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
