# Generated by Django 2.2.3 on 2019-09-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190910_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliedjob',
            options={'verbose_name_plural': 'Applied Jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name_plural': 'Job Types'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matched Jobs'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='postedjob',
            options={'verbose_name_plural': 'Posted Jobs'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={},
        ),
        migrations.AlterModelOptions(
            name='verification',
            options={'verbose_name_plural': 'Verified Payments'},
        ),
    ]
