# Generated by Django 2.2.3 on 2019-08-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190819_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='slug',
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='skills',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
