# Generated by Django 2.2.3 on 2019-08-01 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190730_0959'),
        ('jobs', '0002_auto_20190801_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.Experience')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.JobType')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.Skills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
