# Generated by Django 2.2.3 on 2019-08-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amount_paid',
        ),
    ]
