# Generated by Django 2.2.3 on 2019-08-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190801_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='other',
            new_name='title',
        ),
    ]
