# Generated by Django 2.2.3 on 2019-08-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_appliedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjob',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
