# Generated by Django 2.2.3 on 2019-08-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
