# Generated by Django 2.2.3 on 2019-08-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190807_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
