# Generated by Django 2.2.3 on 2019-08-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_appliedjob'),
        ('jobs', '0002_auto_20190801_1103'),
    ]

    operations = [
    ]
