# Generated by Django 2.2.3 on 2019-11-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20191104_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='applied_id',
            new_name='applied',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='posted_id',
            new_name='posted',
        ),
    ]
