# Generated by Django 2.2.3 on 2019-08-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_postedjob_location'),
        ('jobs', '0004_merge_20190801_1140'),
    ]

    operations = [
    ]
