# Generated by Django 2.2.3 on 2019-08-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_verification_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='paid_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
