# Generated by Django 2.2.3 on 2019-08-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190801_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='working_time',
        ),
        migrations.AddField(
            model_name='postedjob',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postedjob',
            name='working_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
