# Generated by Django 2.2.3 on 2019-08-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190807_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.ImageField(upload_to='banner')),
                ('login_register', models.ImageField(upload_to='banner')),
                ('dashboard', models.ImageField(upload_to='banner')),
                ('newsfeed', models.ImageField(upload_to='banner')),
                ('newsfeed_detail', models.ImageField(upload_to='banner')),
                ('job', models.ImageField(upload_to='banner')),
            ],
        ),
    ]
