# Generated by Django 2.2.3 on 2019-09-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_verification_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjob',
            name='number_of_employee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
