# Generated by Django 2.2.3 on 2019-08-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190801_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facility'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skill'},
        ),
        migrations.RemoveField(
            model_name='postedjob',
            name='facility',
        ),
        migrations.AddField(
            model_name='postedjob',
            name='facility',
            field=models.ManyToManyField(to='jobs.Facility'),
        ),
    ]
