# Generated by Django 2.2.3 on 2019-09-17 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190916_1016'),
        ('jobs', '0006_auto_20190915_1509'),
    ]

    operations = [
    ]
