# Generated by Django 2.2.3 on 2019-08-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190802_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postedjob',
            name='skills',
        ),
        migrations.AddField(
            model_name='postedjob',
            name='skills',
            field=models.ManyToManyField(to='jobs.Skills'),
        ),
    ]
