# Generated by Django 2.2.3 on 2019-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_banner_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='dashboard',
            field=models.ImageField(default='default.jpg', upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.ImageField(default='default.jpg', upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='job',
            field=models.ImageField(default='default.jpg', upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='login_register',
            field=models.ImageField(default='default.jpg', upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='newsfeed',
            field=models.ImageField(default='default.jpg', upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='newsfeed_detail',
            field=models.ImageField(default='default.jpg', upload_to='banner'),
        ),
    ]
