# Generated by Django 2.2.3 on 2019-10-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_merge_20190917_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='skills',
            field=models.ManyToManyField(blank=True, to='jobs.Skills'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='skills',
            field=models.ManyToManyField(blank=True, to='jobs.Skills'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
