# Generated by Django 2.2.3 on 2019-09-06 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_exchange'),
        ('jobs', '0005_postedjob_number_of_employee'),
    ]

    operations = [
    ]
