# Generated by Django 2.2.3 on 2019-08-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20190802_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='facility',
            field=models.ManyToManyField(blank=True, null=True, to='jobs.Facility'),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='jobs.Skills'),
        ),
    ]
