# Generated by Django 2.2.3 on 2019-08-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_banner_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='app_bg',
            field=models.ImageField(default='default.jpg', upload_to='banner'),
        ),
    ]
