# Generated by Django 2.2.3 on 2019-08-04 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20190802_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-briefcase', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='title',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobType'),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
