# Generated by Django 2.2.3 on 2019-08-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20190802_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-briefcase', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='title',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
