# Generated by Django 2.2.3 on 2019-10-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20191022_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='skills',
            unique_together={('job_type', 'title')},
        ),
    ]
