# Generated by Django 2.2.3 on 2019-08-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='applied_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='posted_id',
            field=models.IntegerField(unique=True),
        ),
    ]
