# Generated by Django 2.2.3 on 2019-08-04 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20190804_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
