# Generated by Django 2.2.3 on 2019-08-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20190814_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='applied_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='posted_id',
            field=models.IntegerField(),
        ),
    ]
