# Generated by Django 2.2.3 on 2019-10-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20191022_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
