# Generated by Django 2.2.3 on 2019-08-04 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20190804_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobType'),
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='skills',
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='jobs.Skills'),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
