# Generated by Django 2.2.3 on 2019-08-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_match_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.FloatField(),
        ),
    ]
