# Generated by Django 2.2.3 on 2019-08-05 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20190802_1424'),
        ('jobs', '0013_auto_20190804_0945'),
    ]

    operations = [
    ]
