# Generated by Django 2.2.3 on 2019-10-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20191022_1021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('job_type', 'title')},
        ),
    ]
