# Generated by Django 2.2.3 on 2019-10-22 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20191022_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together=set(),
        ),
    ]
