# Generated by Django 2.1.1 on 2019-11-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_employeer',
            name='no_of_room',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house_employeer',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
