# Generated by Django 2.1.1 on 2019-11-12 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20191112_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_employeer',
            name='other',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
