# Generated by Django 2.1.1 on 2019-11-12 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0003_house_employeer_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('floor', models.IntegerField()),
                ('no_of_room', models.IntegerField()),
                ('direction_faced', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='house_employeer',
            name='user',
        ),
        migrations.DeleteModel(
            name='house_employeer',
        ),
    ]
