# Generated by Django 2.1.1 on 2019-11-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20191112_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerpost',
            options={'verbose_name_plural': 'House detail posted by Seller'},
        ),
    ]
