# Generated by Django 2.1.1 on 2019-11-14 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0008_auto_20191113_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('no_of_room', models.IntegerField()),
                ('direction_faced', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'House detail posted by Buyer',
            },
        ),
    ]
