# Generated by Django 2.1.1 on 2019-11-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_buyerpost_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpost',
            name='contact',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sellerpost',
            name='contact',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
