# Generated by Django 2.1.1 on 2019-11-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_auto_20191118_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='buyerpost',
            name='facility',
            field=models.ManyToManyField(to='house.Facility'),
        ),
        migrations.AddField(
            model_name='sellerpost',
            name='facility',
            field=models.ManyToManyField(to='house.Facility'),
        ),
    ]
