# Generated by Django 2.1.1 on 2019-11-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_auto_20191118_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpost',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
