# Generated by Django 2.2.3 on 2019-09-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
