# Generated by Django 2.2.3 on 2019-09-12 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190912_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Job Seeker', 'Job Seeker')], max_length=15),
        ),
    ]
