# Generated by Django 2.2.3 on 2019-07-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('seeker', 'seeker'), ('giver', 'giver')], max_length=15),
        ),
    ]
