# Generated by Django 2.2.3 on 2019-09-17 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190913_1646'),
        ('users', '0005_auto_20190916_1016'),
    ]

    operations = [
    ]
